image: docker:20.10.5
services:
  - docker:20.10.5-dind
stages:
  - deploy
  - test

deploy:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_LOGIN -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_URL
#    - docker build -t $CI_REGISTRY/nikita_kuznetsov/cicd/python-api:latest .
#    - docker push $CI_REGISTRY/nikita_kuznetsov/cicd/python-api:latest
  only:
    - master
  when: manual

test:
  stage: test
  when: manual
  script:
    - docker login -u $CI_REGISTRY_LOGIN -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_URL
    - docker pull hello-world
    - docker run --rm hello-world
#    - docker pull $CI_REGISTRY/nikita_kuznetsov/cicd/python-api:latest
#    - docker run -dt --name api --expose 5290 $CI_REGISTRY/nikita_kuznetsov/cicd/python-api
#    - sleep 10s
#    - docker ps
#    - docker exec api curl localhost:5290/get_info
#    - docker stop api
