version: '3.8'

services:
  nginx:
    build: nginx
    environment:
      NODE_ENV: production
      PORT: 3000
      TZ: Europe/Moscow
    ports:
      - "20443:443"
    volumes:
      - ssl:/etc/letsencrypt

volumes:
  ssl:
